In [45]:
import pandas as pd 
import os 
import numpy as np

In [46]:
RANDOM_SEED = 42

In [47]:
### Combining all the datasets 
silo_path = '../silos_datasets/'
datasets = []

for filename in os.listdir(silo_path):
    if filename.endswith('.csv'):
        filepath = os.path.join(silo_path, filename) ### Creating a file path for each directory
        data = pd.read_csv(filepath)
        datasets.append(data)
    
combined_datasets = pd.concat(datasets, ignore_index=True)
combined_datasets.head(5)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,60453,94,1,1,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,53904,63,1,1,0,0,0,0,0.000000,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,80,83165164,7,6,354,11595,348,0,50.571429,131.172732,...,20,51.0,0.0,51,51,83100000.0,0.0,83100000,83100000,DoS Hulk
3,80,85013328,6,6,361,11595,361,0,60.166667,147.377633,...,32,1014.0,0.0,1014,1014,84900000.0,0.0,84900000,84900000,DoS Hulk
4,80,83303368,8,5,337,11595,337,0,42.125000,119.147493,...,32,1011.0,0.0,1011,1011,83200000.0,0.0,83200000,83200000,DoS Hulk

In [48]:
print(combined_datasets[' Label'].value_counts())
attack_data = combined_datasets[combined_datasets[' Label'] != 'BENIGN']
non_attack_data = combined_datasets[combined_datasets[' Label'] == 'BENIGN']
print("----------")
print(f" Total attack samples are {attack_data.shape[0]}")
print(f"Total non-attack samples are {non_attack_data.shape[0]}")

 Label
BENIGN                    556488
DoS Hulk                  230124
PortScan                  158804
DDoS                      128025
DoS GoldenEye              10293
FTP-Patator                 7935
SSH-Patator                 5897
DoS slowloris               5796
DoS Slowhttptest            5499
Bot                         1956
Web Attack Brute Force      1507
Web Attack XSS               652
Name: count, dtype: int64
----------
 Total attack samples are 556488
Total non-attack samples are 556488

In [49]:
### Binary classed for each of the silos 
pd1 = pd.read_csv('../silos_datasets/siloOne.csv')
pd1

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,60453,94,1,1,0,0,0,0,0.000000,0.000000,...,32,0.000000e+00,0.0000,0,0,0.000000e+00,0.000000e+00,0,0,BENIGN
1,53904,63,1,1,0,0,0,0,0.000000,0.000000,...,32,0.000000e+00,0.0000,0,0,0.000000e+00,0.000000e+00,0,0,BENIGN
2,80,83165164,7,6,354,11595,348,0,50.571429,131.172732,...,20,5.100000e+01,0.0000,51,51,8.310000e+07,0.000000e+00,83100000,83100000,DoS Hulk
3,80,85013328,6,6,361,11595,361,0,60.166667,147.377633,...,32,1.014000e+03,0.0000,1014,1014,8.490000e+07,0.000000e+00,84900000,84900000,DoS Hulk
4,80,83303368,8,5,337,11595,337,0,42.125000,119.147493,...,32,1.011000e+03,0.0000,1011,1011,8.320000e+07,0.000000e+00,83200000,83200000,DoS Hulk
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503419,80,63095538,7,0,0,0,0,0,0.000000,0.000000,...,40,7.008270e+06,0.0000,7008270,7008270,1.870000e+07,1.220000e+07,32000000,8023641,DoS Slowhttptest
503420,80,218,2,0,0,0,0,0,0.000000,0.000000,...,32,0.000000e+00,0.0000,0,0,0.000000e+00,0.000000e+00,0,0,DoS Hulk
503421,443,2087714,11,6,1045,1375,432,0,95.000000,158.564813,...,32,0.000000e+00,0.0000,0,0,0.000000e+00,0.000000e+00,0,0,BENIGN
503422,80,60492231,10,10,430,168,382,0,43.000000,119.127383,...,20,6.517517e+04,35992.9829,138645,50332,9.996616e+06,1.013091e+04,10000000,9976221,BENIGN
503423,53,31971,2,2,66,190,33,33,33.000000,0.000000,...,20,0.000000e+00,0.0000,0,0,0.000000e+00,0.000000e+00,0,0,BENIGN

In [50]:
print(pd1[' Label'].value_counts())

 Label
BENIGN              251712
DoS Hulk            230124
DoS GoldenEye        10293
DoS slowloris         5796
DoS Slowhttptest      5499
Name: count, dtype: int64

In [51]:
pd2 = pd.read_csv('../silos_datasets/siloTwo.csv')
pd2.head(5)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,52742,26932,2,1,44,6,38,6,22.0,22.627417,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,39839,52,1,1,0,0,0,0,0.0,0.000000,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,5950,48,1,1,0,6,0,0,0.0,0.000000,...,40,0.0,0.0,0,0,0.0,0.0,0,0,PortScan
3,53,411,2,2,94,542,47,47,47.0,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,705,11,1,1,2,6,2,2,2.0,0.000000,...,24,0.0,0.0,0,0,0.0,0.0,0,0,PortScan

In [52]:
print(pd2[' Label'].value_counts())

 Label
BENIGN      288785
PortScan    158804
DDoS        128025
Bot           1956
Name: count, dtype: int64

In [53]:
pd3 = pd.read_csv('../silos_datasets/siloThree.csv')
pd3.head(5)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,21,221,2,1,14,0,14,0,7.000000,9.899495,...,32,0.0,0.000,0,0,0.0,0.00000,0,0,FTP-Patator
1,53,612792,1,1,48,148,48,48,48.000000,0.000000,...,20,0.0,0.000,0,0,0.0,0.00000,0,0,BENIGN
2,443,110219468,24,27,15380,2414,3050,0,640.833333,1051.835070,...,20,1057008.5,2151750.002,5228249,23580,9962586.9,48857.08944,10000000,9850722,BENIGN
3,53,37750,2,2,54,86,27,27,27.000000,0.000000,...,32,0.0,0.000,0,0,0.0,0.00000,0,0,BENIGN
4,88,755,2,2,504,2884,252,252,252.000000,0.000000,...,20,0.0,0.000,0,0,0.0,0.00000,0,0,BENIGN

In [54]:
print(pd3[' Label'].value_counts())

 Label
BENIGN         13832
FTP-Patator     7935
SSH-Patator     5897
Name: count, dtype: int64

In [55]:
pd4 = pd.read_csv('../silos_datasets/siloFour.csv')
pd4.head(5)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,117286545,21,18,710,4414,357,0,33.809524,106.783247,...,32,190673.1818,529211.8730,1786307,31007,1.000000e+07,4365.02479,10000000,10000000,BENIGN
1,80,5243646,3,1,0,0,0,0,0.000000,0.000000,...,32,0.0000,0.0000,0,0,0.000000e+00,0.00000,0,0,Web Attack XSS
2,53,31216,1,1,64,130,64,64,64.000000,0.000000,...,20,0.0000,0.0000,0,0,0.000000e+00,0.00000,0,0,BENIGN
3,53,31368,2,2,72,236,36,36,36.000000,0.000000,...,20,0.0000,0.0000,0,0,0.000000e+00,0.00000,0,0,BENIGN
4,443,61143903,15,14,982,7291,698,0,65.466667,184.588681,...,32,260864.8333,175721.8448,619555,188857,9.929724e+06,316284.11450,10200000,9298227,BENIGN

In [56]:
print(pd4[' Label'].value_counts())

 Label
BENIGN                    2159
Web Attack Brute Force    1507
Web Attack XSS             652
Name: count, dtype: int64

### Silo 4 contributes fewer samples due to the natural scarcity of web attack traffic, reflecting real world heterogenity in federated environments.

### Converting all the silos to binary

In [57]:
def binary_silos_converter(df):
    df = df.copy()
    df['Label_Binary'] = df[' Label'].apply(lambda x: 0 if x == 'BENIGN' else 1)
    df = df.drop(columns = ' Label')
    return df

In [65]:
pd1_binary = binary_silos_converter(pd1)
print(pd1_binary['Label_Binary'].value_counts())
pd1_binary.to_csv('../silos_datasets/SiloBinaryOne.csv')

Label_Binary
0    251712
1    251712
Name: count, dtype: int64

In [66]:
### Creating the pd2_binary 
pd2_binary = binary_silos_converter(pd2)
print(pd2_binary['Label_Binary'].value_counts())
pd2_binary.to_csv('../silos_datasets/SiloBinaryTwo.csv')

Label_Binary
0    288785
1    288785
Name: count, dtype: int64

In [69]:
pd3_binary = binary_silos_converter(pd3)
print(pd3_binary['Label_Binary'].value_counts())
pd3_binary.to_csv('../silos_datasets/SiloBinaryThree.csv')

Label_Binary
1    13832
0    13832
Name: count, dtype: int64

In [70]:
pd4_binary = binary_silos_converter(pd4)
print(pd4_binary['Label_Binary'].value_counts())
pd4_binary.to_csv('../silos_datasets/SiloBinaryFour.csv')

Label_Binary
0    2159
1    2159
Name: count, dtype: int64

In [ ]:
## Creating the combined dataset
binary_combined_dataset = pd.concat()